export const QUOTE_STATUSES = [
    "DRAFT",
    "SENT",
    "ACCEPTED",
    "REJECTED",
    "EXPIRED",
    "PENDING_PAYMENT"
];
export const QUOTE_ITEM_TYPES = ["INVENTORY_PART", "MANUAL_ITEM", "SERVICE", "EXTRA_TEMPLATE"];
