export const SERVICE_TYPES = [
    "SPARE_PART_SALE",
    "PC_CLEANING",
    "FORMATTING",
    "OS_INSTALLATION",
    "DIAGNOSTIC",
    "THERMAL_PASTE_CHANGE",
    "PARTIAL_ASSEMBLY",
    "HOME_SERVICE",
    "OTHER"
];
export const SERVICE_STATUSES = ["PENDING", "COMPLETED", "CANCELLED"];
