import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
function isInventoryPrebuiltBuild(build) {
    return build.items?.length === 1 && build.items[0]?.part?.inventoryKind === "PREBUILT_PC";
}
export function BuildsList({ builds, loading, updatingId, deletingId, onEdit, onDelete }) {
    if (loading) {
        return (_jsx("section", { className: "rounded-2xl border border-slate-800 bg-slate-900/80 p-6 shadow-lg shadow-slate-950/40", children: _jsx("p", { className: "text-sm text-slate-300", children: "Cargando montajes..." }) }));
    }
    if (builds.length === 0) {
        return (_jsx("section", { className: "rounded-2xl border border-slate-800 bg-slate-900/80 p-6 shadow-lg shadow-slate-950/40", children: _jsx("p", { className: "text-sm text-slate-300", children: "Todav\u00EDa no has creado montajes." }) }));
    }
    return (_jsx("section", { className: "grid grid-cols-1 gap-4 lg:grid-cols-2", children: builds.map((build) => (_jsxs("article", { className: "rounded-2xl border border-slate-800 bg-slate-900/80 p-5 shadow-lg shadow-slate-950/40", children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { className: "flex min-w-0 flex-wrap items-center gap-2", children: [_jsx("h3", { className: "text-lg font-semibold text-slate-100", children: build.name }), isInventoryPrebuiltBuild(build) ? (_jsx("span", { className: "shrink-0 rounded-full border border-violet-500/35 bg-violet-500/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-violet-200", children: "PC inventario" })) : null] }), _jsx("span", { className: `rounded-full border px-2.5 py-1 text-xs font-semibold ${build.status === "SOLD"
                                ? "border-cyan-500/40 bg-cyan-500/15 text-cyan-300"
                                : build.status === "CONFIRMED"
                                    ? "border-emerald-500/40 bg-emerald-500/15 text-emerald-300"
                                    : "border-amber-500/40 bg-amber-500/15 text-amber-300"}`, children: build.status === "SOLD" ? "Vendido" : build.status === "CONFIRMED" ? "Assembled" : "Draft" })] }), _jsx("p", { className: "mt-2 text-sm text-slate-300", children: build.notes || "Sin descripción." }), (build.status === "CONFIRMED" || build.status === "SOLD") && build.totalSale !== undefined ? (_jsxs("p", { className: "mt-3 text-sm font-semibold text-emerald-300", children: ["Precio venta: ", Number(build.totalSale).toFixed(2), " EUR"] })) : null, _jsxs("p", { className: "mt-4 text-xs text-slate-400", children: ["Piezas: ", build.items?.length ?? 0] }), _jsxs("div", { className: "mt-4 flex flex-wrap gap-2", children: [_jsx(Link, { to: `/builds/${build.id}`, className: "inline-flex rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-indigo-900/40 transition hover:bg-indigo-500", children: "Ver detalle" }), build.status === "CONFIRMED" ? (_jsx(Link, { to: `/builds/${build.id}#registrar-venta`, className: "inline-flex rounded-lg bg-cyan-600 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-cyan-900/30 transition hover:bg-cyan-500", children: "Registrar venta" })) : null, _jsx("button", { type: "button", onClick: () => onEdit(build), disabled: updatingId === build.id || build.status === "SOLD", className: "inline-flex rounded-lg border border-amber-500/40 bg-amber-500/10 px-4 py-2 text-sm font-semibold text-amber-200 transition hover:bg-amber-500/20 disabled:cursor-not-allowed disabled:opacity-50", children: updatingId === build.id ? "Guardando..." : "Editar" }), _jsx("button", { type: "button", onClick: () => onDelete(build), disabled: deletingId === build.id || build.status === "SOLD", className: "inline-flex rounded-lg border border-rose-500/40 bg-rose-500/10 px-4 py-2 text-sm font-semibold text-rose-200 transition hover:bg-rose-500/20 disabled:cursor-not-allowed disabled:opacity-50", children: deletingId === build.id ? "Eliminando..." : "Eliminar" })] })] }, build.id))) }));
}
